### ISSUE TITLE
RFA003: Rename foundation to organisation-foundation and services-implementation to implementation.

### ISSUE THREAD

**Issue by jamalv** [teamforus/foundation#10]
## Problem statement:
There is currently some confusion about the difference between the foundation and organisation repositories.

## Proposed solution:
Foundation should probably not be a "top level" repository. We can rename it to organisation-foundation. This makes space for one more pinned repository and I think implementation best fits here. Now it is named as service-implementation, but that would then simply be implementation.

This makes us end up with the following top level repo’s (open source):

**me**
**forus.io**
**research-and-development**
**implementation**
**organisation**
**service**

This issue supersedes: https://github.com/teamforus/organisation/issues/6

**Comment by maxvisser** [comment]
whats the difference than between service and implementation?

**Comment by maartenfv** [comment]
I would say organisation and foundation are the same and we can stick with organisation in the naming structure.

I think that service could have a couple sub repositories like implementation and support.

Would do you guys think of something like this?

- me (core product)
- forus.io (core product)
- research-and-development (general research)
- organisation
  - organisation-internal (working for the foundation)
  - organisation-finance
  - organisation-direction
  - organisation-communication
    - organisation-communication-foundation.forus.io
    - organisation-communication-chat.forus.io
- service
  - service-implementation (implementation of the core products)
    - service-implementation-forus.io&me-Kindpakket-Zuidhorn
    - service-implementation-forus.io&me-Kindpakket-Westerkwartier
    - service-implementation-forus.io&me-Kindpakket-Emmen
    - service-implementation-forus.io&me-02coins-Longfonds
     - service-implementation-forus.io&me-Stemapp-BendeVanVijf
    - service-implementation-me-eigenschap-Groningen&RVIG
    - service-implementation-me-eigendom-Kadaster
  - service-support

**Comment by maxvisser** [comment]
why do we want so many organisational repo's exactly? why not just label the issues and sort/filter them?

**Comment by maartenfv** [comment]
@maxvisser We have discussed this issue in real life. How shall we continue?

**Comment by maxvisser** [comment]
we decided to not use any domain names in repo names for the development repo's. also that organisation is foundation. Did we decide anything about organisation and organisation-internal?

**Comment by maxvisser** [comment]
- me (core product)
- forus (core product)
   - forus-internal (changed from organisation-internal)
- research-and-development (general research)
- foundation
  - foundation-internal (working for the foundation)
  - foundation-finance
  - foundation-direction
  - foundation-communication
    - foundation-site
    - foundation-chat
- support (implementation of the core products)
    - implementation-westerkwartier
    - implementation-emmen
    - implementation-longfonds
    - implementation-bendevanvijf
    - implementation-groningen
    - implementation-kadaster
- support (service is changed to support)

**Comment by jamalv** [comment]
- me (core product)
- forus (core product)
- research-and-development (general research)
- organisation
  - organisation-internal
  - organisation-foundation-internal (working for the foundation, offertes etc.)
  - organisation-foundation-finance
  - organisation-foundation-direction
  - organisation-foundation-communication
  - organisation-foundation-site
  - organisation-chat
- implementation (implementation of the core products)
    - implementation-westerkwartier
       - implementation-westerkwartier-survey
    - implementation-emmen
    - implementation-longfonds
    - implementation-bendevanvijf
    - implementation-groningen
    - implementation-kadaster
- support (changed from service)

**Comment by jamalv** [comment]
After the update, moving issues to appropriate repositories is pretty important, and adding a (initially short) readme will also help. It might be a little bit confusing at first, but I don't think it will be too bad.

**Comment by jamalv** [comment]
p.s. the main reasoning behind having an "organisation" top level repository is for organising the efforts of participating people, including those that might not be directly related to the foundation. this current issue (the naming of repositories) is a good example of an issue that fits this. also updating info on wiki pages etc. Feedback on this repo was that "organisation" might be a bit abstract, but I think that can actually be considered a positive, it makes this repo quite flexible.

possible sub-repo's include

organisation-foundation
organisation-community
organisation-association
organisation-commonground
organisation-bendevanvijf
organisation-redcross-simbabwe

<img width="340" alt="screen shot 2018-06-27 at 21 45 07" src="https://user-images.githubusercontent.com/30194799/41995865-6a368afe-7a53-11e8-85b7-d2700b319472.png">

**Comment by jamalv** [comment]
I like that picture. Maarten and I were having some more abstract discussions that could influence this. By using the top-level repo's as much as possible and just clearly labeling the issues, we might not need so many sub repo's. Sub repo's are now mainly about controlling who can see what.

@maartenfv what are your thoughts on this?

**Comment by maxvisser** [comment]
@martijndoornik that would mean we think up a different name for organisation-internal. Maybe retrospective?

**Comment by martijndoornik** [comment]
The Internal is the only private one, right? Why not call it organisation-private?

**Comment by maxvisser** [comment]
imo the plan is to rename foundation-internal to organisation-internal and organisation-internal to something else. ;) If we change it to organisation-private. it's get confusing (it is already, lets not make it more confusing than needed)

**Comment by maxvisser** [comment]
I thought about it a bit more. The idea of an organisation part to our github is still to vague to implement. I personally think for the sake of github adoption we should just keep foundation as is. Therefore implementation would replace organisation and organisation-internal could be foundation-development.

- me (core product)
- forus (core product)
- research-and-development (general research)
- foundation
  - foundation-internal (working for the foundation, offertes etc.)
  - foundation-development (changed from organisation-internal)
  - foundation-finance
  - foundation-direction
  - foundation-communication
  - foundation-site
  - foundation-chat
- implementation (implementation of the core products)
    - implementation-westerkwartier
       - implementation-westerkwartier-survey
    - implementation-emmen
    - implementation-longfonds
    - implementation-bendevanvijf
    - implementation-groningen
    - implementation-kadaster
- support (changed from service, maybe even delete it if Gerben sees no use case for it)

**Comment by jamalv** [comment]
Implemented.
