### ISSUE TITLE
Generate website content from /docs folder using github/gitlab pages.

### ISSUE THREAD

**Issue by jamalv** [teamforus/foundation#12]
## Proposal:

To add all the website texts to a /docs folder in this repository, and generate the website from that using github pages, effectively using github as a CMS. The main advantage is that we can use git(hub) for the content manament of our website, enabling easier collaboration and also having the contents of this repository automatically in sync.

This idea needs some research/testing to see if it is feasible.

**Comment by martijndoornik** [comment]
In a quick Google-Fu session I found that RawGit can get a file from a public Github, ready for you to read. ([Example](https://cdn.rawgit.com/teamforus/rd-ethereum-eventhub-azure/2ebbd716b19b7a5832adee0e723e0122ddfb0524/README.md))

Now, from there on, there is a plugin called "Showdownjs", which seems to be able to transform markdown into HTML ([Showdown Github](https://github.com/showdownjs/showdown))

**Comment by jamalv** [comment]
There is also a first-party solution available: https://pages.github.com

Maybe the whispers of a impending gitlab migration change our perspective on this issue tough :)

**Comment by GerbenBosschieter** [comment]
@jamalv nope, IMO it doesn't have to change our opinion. GitLab has the same thing as GitHub with even more features (https://about.gitlab.com/comparison/gitlab-pages-vs-github-pages.html)

It also supports all Jekkyl features and markdown to html

**Comment by jamalv** [comment]
Hmm, interesting! Gitlab is becoming more and more attractive :)

**Comment by jamalv** [comment]
Similar issue opened: https://github.com/teamforus/knowledge-base/issues/3

To clarify, this specific issue is about investigating if we can (and should) use GitHub / GitLab pages to replace our current Django CMS.

**Comment by jamalv** [comment]
closing this issue at least until we start work on our new website.
