### ISSUE TITLE
Make Forus and me project boards open to the public

### ISSUE THREAD

**Issue by maxvisser** [teamforus/foundation#14]
## Problem statement:
Currently the me and forus project boards are team forus eyes only. Is ee no reason for this; all issues are open and impedements are removed from the boards.

## Proposed solution:
I propose to open them up to the public.

Will do this and maybe share it with stake holders?

**Comment by jamalv** [comment]
Seems good to me. Let's do it.

**Comment by jamalv** [comment]
Done.
