### ISSUE TITLE
Set up demo booth

### ISSUE THREAD

**Issue by jamalv** [teamforus/foundation#16]
## Problem statement:
Right now it is pretty difficult for everybody (internal organisation + stakeholders) to stay up to date with the status of our product development.

## Proposed solution:
It has been proposed to set up a demo station. It will need a computer that has access to the test environment, and two smartphones (Android and iOS). It should be super simple for anybody to play around and get a feel for the current status of the product.

## Requirements:
* Budget @TomForus @maartenfv, what do you think about this idea?
* (Old) devices
  * iPhone
  * Android phone
  * Computer + screen
  * Dedicated location: table or something

<details>
  <summary>Comments on original issue</summary>
@GerbenBosschieter:
I will think of a set up for a demo booth, there are probably going to be some financial costs. I am going and present a proposal to @TomForus and @maartenfv so they decide.

@martijndoornik:
I we do so, I suggest using a web app and something like Instant Apps*. This way, we can guarantee that we are only using the latest version

*: Instant apps are apps that run in the browser of the phone, without installation. I know it's called like that in Android, not sure in iOs. Link: https://developer.android.com/topic/google-play-instant/
</details>

**Comment by jamalv** [comment]
Android phone has been provided by @danrminds, so just need an iPhone and a computer. @danrminds I believe the app now has been optimised for the iPhone 6 screen size, right?

@GerbenBosschieter how much would it be to repair the screen of the test iPhone you use now?

**Comment by maartenfv** [comment]
I am very down for this one. Tangible is better. Would also support a modest investment.

**Comment by GerbenBosschieter** [comment]
@jamalv A new screen is about 40 euro's. It's possible to do it by our self, but I also know someone who works at a phone shop and already offered me to replace the screen is I buy the screen.

**Comment by jamalv** [comment]
So I would say 40 euros is part of the modest investment, so let’s do this :)

**Comment by jamalv** [comment]
First itteration has been made, now it is a matter of improving it step by step.
