### ISSUE TITLE
What does it mean to be a maintainer?

### ISSUE THREAD

**Issue by jamalv** [teamforus/foundation#17]
## Context
We have started to assign maintainers to repo's and project boards. But it is currently unclear what it means to be a maintainer. This issue is meant to gather a shared picture, and to add the results to the wiki.

**Comment by maxvisser** [comment]
Closing all issues after 2 weeks if there is no development or updates from assignees

maintaining readme files

chosing if a wiki, issue section and or project boards are necassery for this specific repo. If you don't use it, disable it.

**Comment by jamalv** [comment]
made a start here to iterate on: https://github.com/teamforus/foundation/wiki/The-maintainer-manual
