### ISSUE TITLE
Create docs repo

### ISSUE THREAD

**Issue by jamalv** [teamforus/foundation#19]
## Problem statement

Right now we are creating docs folders in every repository, e.g. [forus](https://github.com/teamforus/forus/tree/dev/docs) and [me](https://github.com/teamforus/me/tree/develop/docs/standards) and we are also starting to use wiki's. Sometimes it becomes quite hard to decide where some piece of info needs to go / is located since it can be relevant for multiple repositories. (e.g. a piece about ethereum fits the me repo, the forus repo and the r&d repo. Our way of working & values are relevant for everything)

## Proposed solution

Looking at the rocket.chat GitHub: https://github.com/RocketChat they place all their docs in one repo and generate a website / knowledge base from that: https://rocket.chat/docs/ I propose we do the same, using the index page to split up the contents of the docs based on different projects / topics. But have all the documentation in one big knowledge base. Each repo should still have a readme where the contents of the repo get explained and were links to the knowledge base relevant articles can be added.

Index page example:
* me
* forus
* foundation
* implementation

If you agree, please give this a thumbs up 👍

**Comment by maxvisser** [comment]
Discussed this with jamal. We will make a seprate repo for the knowledge base. And make seperate submodules for each folder

**Comment by maartenfv** [comment]
Maybe plan a moment where you show the new practice to everybody? @maxvisser

**Comment by jamalv** [comment]
Repo has been created, itteration has started: 
https://github.com/teamforus/docs
