### ISSUE TITLE
Job satisfaction as a key metric

### ISSUE THREAD

**Issue by maartenfv** [teamforus/foundation#23]
Today we had a direction discussion regarding some of the key metrics we would like to use to guide our organisation. One of the primary metrics was job satisfaction.

I have spoken with @sloppyrocket aka Nikita Shabankin Msc. psychology regarding our issue. He recommended the following survey to index job satisfaction. I think it will be very use full.

The study: [Download full document](https://chat.forus.io/file-upload/EqvKmGNrSKdQrDxzc/Test_manual_UWES_English.pdf)

@maxvisser Could we train Maxbot to ask these questions once every month (or so) to each of the team members? Could we have the results processed and spat our in the team channel?

In general: What do you guys think about implementing this?

### Work & Well-being Survey

The following 17 statements are about how you feel at work. Please read each statement carefully and decide if you ever feel this way about your job. If you have never had this feeling, cross the ‘0’ (zero) in the space after the statement. If you have had this feeling, indicate how often you feel it by crossing the number (from 1 to 6) that best describes how frequently you feel that way.

0 Never
1 Almost never - A few times a year or less
2 Rarely - Once a month or less
3 Sometimes - A few times a month or less
4 Often - Once a week
5 Very often - A few times a week
6 Always - Everyday

1. ________ At my work, I feel bursting with energy* (VI1)
2. ________ I find the work that I do full of meaning and purpose (DE1)
3. ________ Time flies when I'm working (AB1)
4. ________ At my job, I feel strong and vigorous (VI2)*
5. ________ I am enthusiastic about my job (DE2)*
6. ________ When I am working, I forget everything else around me (AB2)
7. ________ My job inspires me (DE3)*
8. ________ When I get up in the morning, I feel like going to work (VI3)*
9. ________ I feel happy when I am working intensely (AB3)*
 10. ________ I am proud on the work that I do (DE4)*
 11. ________ I am immersed in my work (AB4)*
 12. ________ I can continue working for very long periods at a time (VI4)
 13. ________ To me, my job is challenging (DE5)
 14. ________ I get carried away when I’m working (AB5)*
 15. ________ At my job, I am very resilient, mentally (VI5)
16. ________ It is difficult to detach myself from my job (AB6)
17. ________ At my work I always persevere, even when things do not go well (VI6)

**Comment by maartenfv** [comment]
### Completion and scoring

It takes about 5-10 minutes to complete the UWES, which can be done individually as well as group wise. The UWES may be used for individual assessment as well as for group assessment, for instance as part of an employee satisfaction survey, or a psychosocial risk evaluation. The instruction at the top of the UWES test-form is self-evident (see Appendix). If necessary, it can be checked if the subject(s) have understood the instruction.

In order to avoid answering bias that might result from specific connotations related to ‘work engagement’ this term is not used in the title of the questionnaire. Instead, the more neutral term ‘Work & Well-being Survey’ is chosen with UWES between parentheses.

The mean scale score of the three UWES subscales is computed by adding the scores on the particular scale and dividing the sum by the number of items of the subscale involved. A similar procedure if followed for the total score. Hence, the UWES, yields three subscale scores and/or a total score that range between 0 and 6. For the content of the items and the meaning of the scale scores the reader is referred to Chapter 2. 

**Norms can be found on page 34. in the study document**

**Comment by jamalv** [comment]
Big proponent of this, I think it is one of the most vital aspects for us as an organisation. 

I guess in order for the results to be objective and truly honest, they should be anonymous?

**Comment by maxvisser** [comment]
easy way to solve this is using a proper survey tool like survey monkey and send the link to that via maxbot

**Comment by sloppyrocket** [comment]
> I guess in order for the results to be objective and truly honest, they should be anonymous?

The asterisk-marked questions just represent the shortened version, they do not make any additional logic. Every question is straight, not inverted, so it means the higher marks you put – the happier you represent yourself. People tend to put higher socially desirable marks, if the results go public or being sent to a manager.

For the results to be valid and represent morale, they really need to be anonymous, or only available to respondent's confidential view.

The Maxbot can screen people by sending questions and getting numbers back and then make up statistics and graphs, as @maartenfv suggested. As I think, these graphs shouldn't be individual, but statistically they can represent the team's morale. These results may be published somewhere only members can see.

**Comment by maartenfv** [comment]
Made a start with the questionnaire in google sheets: https://docs.google.com/forms/d/1ZLw4NqInxBzrzG9il85m6UDfkfLkJgPSSpZlkUR_Ntw/edit?usp=sharing.
It needs some more styling and a way to share the results.

**Comment by sloppyrocket** [comment]
I added scale explanation in the instructions field. Think, people should always mind what each number stands for.

**Comment by jamalv** [comment]
Google forms doesn't seem to fulfil the requirement of anonymity (at least in its current form).

**Comment by sloppyrocket** [comment]
Google.forms can be rather anonymous, when you get to that survey via link that has been sent directly to you. The excel table then being created and it records people's answers. If there's no option to record an email address or there's no fields for your name to be filled, then there's no data gathered about who aswered that questions. In that case, you can't figure out who was behind the answers, the only key is the timestamp when it was done.

On the other hand, you can never guess who it was when it was filled multiple times by the same people. To help monitoring dynamics of that survey through multiple takes, you might need to gather a password or a codephrase. E.g. each time I pass it, I fill "ABC-123" in a specific field, and the one who sees the answers only knows which data represents that ABC-123 guy.

**Comment by maartenfv** [comment]
We have updated the google form to be anonymous. 

The form seems to meet the criteria it just needs an instruction to go along with the link when sending it.

Something like:
Please think of a random code that you will use whenever you fill in these surveys. This will allow us to process the results without us knowing who you are.

**Comment by jamalv** [comment]
I would suggest advising everyone to use something like: https://passwordsgenerator.net with the default settings. This way everybody’s randomness is random in a similar way, not exposing anything about their identity. 

Everyone would then themselves be responsible for securely and privately saving this identifier.

**Comment by sloppyrocket** [comment]
We can use this platform: https://surveyjs.io/. I had experience with that, particularily, I had issues to fix with the developer of that platform and he appeared to be a russian guy who I had several test-cases worked out with then.

**Comment by maartenfv** [comment]
Will close this for now as there is no progress.
