### ISSUE TITLE
Daily write-up

### ISSUE THREAD

**Issue by jamalv** [teamforus/foundation#24]
## Context

We have been doing daily standups semi-successfully for the past months. It is very valuable and and an important way to keep the team members synced. 

## Problem
Lately I've been on the road a lot during standup, and due to the time zone / rhythm differences between the team, not everybody is participating in the standups. Also, we have two different standups (dev and organisation), this makes it such that not everybody is able to get a full picture.

## Proposal
I think it would be a good idea to make a write-up channel, where _everybody_ working that day writes down what they did yesterday and will do today. This way it is documented, and possible to read for everybody. It makes it possible to see how the work evolves over time (kind of like a log book) and it solves the time-zone/rhythm/being-in-the-train problems since it can be done asynchronously (if you forget your write-up for a day you should still bring roze koeken, obviously!) 

We can use the same channel to offer each-other help / ask for help on your tasks. The write-up should be supplemented with (more) frequent direct calls and chats in order to be effective, also the team can decide to have a (daily) video check-in if they think it could be beneficial.

**Comment by jamalv** [comment]
The channel can be public. This makes the barrier for outside contributors lower, since everything is open-source anyway. We should al just be mindful of it and use the internal channels for announcements that shouldn't be public (private/personal info etc.)

**Comment by GerbenBosschieter** [comment]
I agree! but I do think its important to keep the stand-ups and don't replace it with write-ups but more the write up as an additional thing.

**Comment by maxvisser** [comment]
I think the sprint demo's would be the normal solution for the problem you are having. I havent heard any complains for timezone issues with the current time of the standup. Rhythm/being-in-the-train seems more like an issue.

**Comment by jamalv** [comment]
Yea, so then maybe we can change the format of the standup a little bit? Really focus it on the third question that now often gets ignored: What risks do I see, and who could help me with that?

**Comment by jamalv** [comment]
@maxvisser, for the write up I would like to see everyone participate, also all team members in Moldova and Russia.

**Comment by maartenfv** [comment]
I think it is important to stay in contact with one another. The stand-up should be leading and a write-up can support it. I do like the idea of being able to scroll back in time and see what everybody has been up to.

**Comment by jamalv** [comment]
I would suggest making the write-up mandatory, at least for two weeks and to enforce it. It is the only way to really see how much value it has. Maybe start with this from the beginning of next sprint?

**Comment by jamalv** [comment]
Also, what are the opinions on doing it in a public channel so that other (potential) contributors, partners and interested parties can see it? Please rate this comment 👍/👎

**Comment by maxvisser** [comment]
@jamalv we started doing standups at 9 am. Thats 10 am in russia and moldova. I dont see why they dont just attend standup. If thats what you want.

**Comment by maxvisser** [comment]
Felt a bit weird doing the writeup before standup. was just reading out loud what I wrote down.

**Comment by jamalv** [comment]
Yea, kinda had the same 😛 Let's maybe plan a call about this somewhere next week? Where we can involve everybody and discuss it for a bit?

**Comment by jamalv** [comment]
Until then this is optional. I think the greatest cost/benefit ratio is just posting a list of the plan for today.

e.g.
> Today:
> - presentation for friday
> - offerte for customer x
> - implement new feature y

**Comment by maxvisser** [comment]
Discussed this today with jamal. I proposed to do it at the end of the day. So basically we start the day with a standup and end the day with a write down.

 
 This way @jastam @martijndoornik and me can do this while writing our hours in timesquare for QNH.

**Comment by jamalv** [comment]
The channel is there and the write up is optional. Opened another issue to vote on making it mandatory for a sprint: https://github.com/teamforus/foundation/issues/25

I think for now this issue can be closed, can be re-opened if there’s additions to the discussion.

**Comment by martijndoornik** [comment]
Considering we have more 'strict' standups now, this can be really closed.
