### ISSUE TITLE
The webshop as our new website on forus.io

### ISSUE THREAD

**Issue by maartenfv** [teamforus/foundation#27]
We are planning on placing the generic webshop on Forus.io.

- Need a plan for the CMS (discussion can take place in this issue)
- Google drive general folder with website: content, wireframes, designs and structure
  - Media&communucation/website nieuw: https://drive.google.com/drive/folders/1ig9PHLiEjhvrwD7JZQyQ3qqHs_iOdFFQ
- We will start with working on the wire-frames and once we agree we will continue towards designs.
  - Wireframes can be found here: https://drive.google.com/drive/folders/1XHtKngGa2pX4U5Y6nUaIZvS3pKW8MdPu
- We can use the ¨informatiepakket as a source for content¨: https://docs.google.com/presentation/d/1oQ-SbbDuUkK-hUAmh6zqlMbmrX4_4vcfiyY1SSAnwKg/edit#slide=id.p

First step for now is determining which pages will be listed in the top menu bar and place them in the wireframes.

**Comment by maxvisser** [comment]
https://docs.google.com/document/d/1xc2EXwIKye_Qx5KKkWcCWCTjfjpZDJKZGSeaAQMwec8/edit?usp=sharing
